Repository jenkinsci/workflow-durable-task-step-plugin, pull requests merged in 2021-09, with the labels that each got.

#167 Make this test compatible with Jenkins 2.307+
  src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
Labels: maintenance

#170 Implement `Queue.Executable.getParentExecutable`
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: enhancement

#168 Change NODE_NAME for the built-in node based on its self label
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
Labels: maintenance

#171 Fix incrementals in PCT
  pom.xml
Labels: internal

#172 Remove deprecated config
  Jenkinsfile
Labels: maintenance

#169 make additional tests compatible with Jenkins 2.307
  src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
Labels: maintenance

#162 Rename PowershellScriptStep to WindowsPowerShellScriptStep
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep.java
  src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep/config-details.jelly
  src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep/help-script.html
Labels: maintenance

#173 Revert "Remove deprecated config (#172)"
  Jenkinsfile
Labels: bug

#174 chore: revert back to 'useContainerAgent' for CI pipeline
  Jenkinsfile
Labels: internal
