Repository jenkinsci/workflow-durable-task-step-plugin, pull requests merged in 2021-12, with the labels that each got.

#185 Recover gracefully when a `PlaceholderTask` is in the queue but the associated build is complete
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: bug

#188 [JENKINS-67531] Do not load Pipelines during PlaceholderTask.getCauseOfBlockage in normal scenarios
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: bug

#189 Add missing nullability annotations and replace JSR 305
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/BatchScriptStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/PowerShellCoreScriptStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep.java
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ComputerPickle.java
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/FilePathPickle.java
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/WorkspaceListLeasePickle.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStep.java
  src/test/java/org/jenkinsci/plugins/workflow/BuildQueueTasksTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: chore

#190 Deleting obsolete `ExecutorStepTest.accessPermittedOnlyFromCurrentBuild`
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: tests
