Repository jenkinsci/workflow-durable-task-step-plugin, pull requests merged in 2021-11, with the labels that each got.

#143 Use `FlagRule`
  src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
Labels: tests

#147 ExecutorStepExecution.queue_task_cancelled should yield ABORTED not FAILURE
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: enhancement

#176 Make `ExecutorPickle` add `RemovedNodeCause`
  Jenkinsfile
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
  src/test/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickleTest.java
Labels: enhancement

#177 Demonstration that implementing `getParentExecutable` is necessary
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: tests, dependencies

#179 Removing dead field `ExecutorPickle.ephemeral`
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
Labels: chore

#181 Add Dependabot configuration
  .github/dependabot.yml
Labels: dependencies

#184 `ExecutorPickle` should not reschedule anything until after `Queue.load`
  src/main/java/org/jenkinsci/plugins/workflow/support/pickles/ExecutorPickle.java
Labels: bug

#81 Reverting custom thread pool from #53 in watch mode
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
Labels: bug
