Repository jenkinsci/workflow-durable-task-step-plugin, pull requests merged in 2022-07, with the labels that each got.

#248 [JENKINS-49707] Cleanups after merge of `node` retry base PR
  pom.xml
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/RetryExecutorStepTest.java
Labels: tests

#249 [JENKINS-49707] `AgentErrorCondition` improvements
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorCondition.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/AgentOfflineException.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/FilePathDynamicContext.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorConditionTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: enhancement

#250 update ShellStepTest to support workflow-support 827.v7ef666c4d65c
  src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
Labels: tests

#227 More inclusive comments - combine #220 and #221
  src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/WorkspaceStepTest.java
Labels: chore

#252 Handle `ChannelClosedException` in `AgentErrorCondition`
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorCondition.java
Labels: bug

#253 Improve `ShellStepTest.label` with Hamcrest
  src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
Labels: tests

#254 [JENKINS-49707] `retry` without conditions should handle node removal
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorConditionTest.java
Labels: bug
