Repository jenkinsci/workflow-durable-task-step-plugin, pull requests merged in 2022-06, with the labels that each got.

#233 [JENKINS-68727] Require 2.332.x
  pom.xml
Labels: bug

#242 Warn when `Queue.cancel` calls fail
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
Labels: bug

#241 Improve `PlaceholderTask.getACL`
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
Labels: bug

#235 chore: use jenkins infra maven cd reusable workflow
  .github/workflows/cd.yaml
Labels: chore

#240 chore: add a note linking the difference between Windows PowerShell and PowerShell Core
  src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowerShellCoreScriptStep/help-script.html
  src/main/resources/org/jenkinsci/plugins/workflow/steps/durable_task/PowershellScriptStep/help-script.html
Labels: documentation
