Repository jenkinsci/workflow-durable-task-step-plugin, pull requests merged in 2023-07, with the labels that each got.

#326 Remove outdated Jenkins version test conditional
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: tests

#323 [JENKINS-52165] Stabilize and better test `USE_WATCHING`
  Jenkinsfile
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/AgentErrorCondition.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: enhancement

#327 Do not even try to use `LogTaskListener`
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
Labels: bug
