Repository jenkinsci/workflow-durable-task-step-plugin, pull requests merged in 2023-08, with the labels that each got.

#330 `build` attribute for `buildProgressBar` should be a `Queue.Executable`, not a `Queue.Task`
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/main/resources/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution/PlaceholderTask/PlaceholderExecutable/executorCell.jelly
Labels: bug

#332 `lastLocation` testing
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: tests

#335 EnvWorkflowTest#isNodeNameAvailable robustness
  src/test/java/org/jenkinsci/plugins/workflow/EnvWorkflowTest.java
Labels: tests

#338 Add Plugin Development Team to CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance
