Repository jenkinsci/workflow-durable-task-step-plugin, pull requests merged in 2024-11, with the labels that each got.

#405 Extending `AnomalousStatus` to also kill `sh` steps
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContext.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepDynamicContextTest.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepTest.java
Labels: enhancement

#407 Fix running tests on MacOS
  src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStepTest.java
  src/test/java/org/jenkinsci/plugins/workflow/steps/durable_task/ShellStepTest.java
Labels: tests

#408 Build fails to resume if controller crashes before queue is saved
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
  src/test/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecutionRJRTest.java
Labels: bug
