Repository jenkinsci/workflow-durable-task-step-plugin, pull requests merged in 2025-01, with the labels that each got.

#415 Handle null `controller` in `DurableTaskStep.Execution.getStatus`
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
Labels: bug

#417 Using `StepExecution.acceptAll`
  pom.xml
  src/main/java/org/jenkinsci/plugins/workflow/steps/durable_task/DurableTaskStep.java
  src/main/java/org/jenkinsci/plugins/workflow/support/steps/ExecutorStepExecution.java
Labels: chore

#421 Remove test harness override
  pom.xml
Labels: skip-changelog

#422 Remove `forkCount`
  Jenkinsfile
Labels: skip-changelog
